FROM tsl0922/musl-cross
RUN git clone --depth=1 https://github.com/tsl0922/ttyd.git /ttyd \
    && cd /ttyd && ./scripts/cross-build.sh x86_64

FROM alpine:3.10
COPY --from=0 /ttyd/build/ttyd /usr/bin/ttyd
COPY scripts/cpu.sh scripts/mem.sh /
RUN chmod +x /cpu.sh /mem.sh && mv /cpu.sh /usr/bin/cpu && mv /mem.sh /usr/bin/mem
RUN apk add --no-cache bash tini atop

VOLUME ["/proc_host", "/logs"]
EXPOSE 7681

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["ttyd", "bash"]
